/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PAT;

import backend.GatorQuestion;
import backend.ChatManager;
import backend.GameMethods;
import PAT.NewUser;
import backend.GameMethods;
import backend.UserManager;
import javax.swing.JProgressBar;
import javax.swing.JButton;
import java.awt.Color;
import backend.GatorOption;
import javax.swing.ImageIcon;

/**
 *
 * @author user-pc
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private int bar_value = 0;
    private int ans_val1 = 0;
    private int ans_val2 = 0;
    private boolean hasPuzzled = false;

    private GameMethods gameMethods;
    private ChatManager chatManager;
    private GatorQuestion currentQuestion;
    private GatorOption currentOption;
    private NewUser user;
    private boolean hasResponded;
    private boolean hasBirded;
    private int currentBarVal;
    
     public int getBarValue() {
        return currentBarVal;
    }
    
    public MainScreen() {
        initComponents();
        gameMethods = new GameMethods();
        chatManager = new ChatManager();
        hasBirded = false;
        hasResponded = false;
        hasResponded = true;
        setQuestionForId("Q1");

        loveBar.setOrientation(loveBar.VERTICAL);
        loveBar.setMinimum(0);
        loveBar.setMaximum(100);
        loveBar.setValue(0);
    }

    private void setQuestionForId(String questionId) {
        currentQuestion = chatManager.questions.get(questionId);
        //System.out.println(currentQuestion.toString());
        if (currentQuestion != null) {
            dialogue_area.setText(currentQuestion.questionText);
            button1.setText(currentQuestion.options[0].optionText);
            button2.setText(currentQuestion.options[1].optionText);
            System.out.println(currentQuestion);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dialogue_area = new javax.swing.JTextArea();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        loveBar = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        nameplace = new javax.swing.JLabel();
        picplace = new javax.swing.JLabel();
        imagearea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1315, 730));
        setPreferredSize(new java.awt.Dimension(1315, 950));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dialogue_area.setEditable(false);
        dialogue_area.setColumns(20);
        dialogue_area.setRows(5);
        jScrollPane1.setViewportView(dialogue_area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 820, 190));

        button1.setText("PLACEHOLDER");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 700, 280, 90));

        button2.setText("PLACEHOLDER");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 800, 280, 90));

        loveBar.setToolTipText("");
        getContentPane().add(loveBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 680));

        jButton1.setText("Quit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, 50));

        nameplace.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        getContentPane().add(nameplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 250, 100));
        getContentPane().add(picplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 190, 290));
        getContentPane().add(imagearea, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1315, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        handleButtonAction((JButton) evt.getSource());

    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed

        handleButtonAction((JButton) evt.getSource());


    }//GEN-LAST:event_button2ActionPerformed

    private void handleButtonAction(JButton target) {
        if (this.currentQuestion == null) {
            EndingScreen end = new EndingScreen();
            end.setVisible(true);
            MainScreen main = new MainScreen();
            main.dispose();
            return;
        }
        hasResponded = !hasResponded;
        button2.setVisible(hasResponded);
        if (!hasResponded) {

            currentOption = (target == this.button1) ? currentQuestion.options[0] : currentQuestion.options[1];
            dialogue_area.setText(currentOption.response);
            button1.setText("Next");
            ImageIcon icon = new ImageIcon(currentOption.optionImage);
            imagearea.setIcon(icon);
            int val = Integer.parseInt(currentOption.barvalue);
            bar_value += val;
            if (bar_value > 100) {
                bar_value = 100;
            }
            if (bar_value < 0) {
                bar_value = 0;
                
            }
             currentBarVal = bar_value;
             loveBar.setValue(bar_value);
             System.out.println(bar_value);
             System.out.println(currentBarVal);
           
            
           
            
        } else {
            setQuestionForId(currentOption.nextQuestionID);
            if (currentQuestion.questionImage != "") {
                ImageIcon icon2 = new ImageIcon(currentQuestion.questionImage);
                imagearea.setIcon(icon2);
                System.out.println(currentQuestion.questionImage);

                if (currentQuestion.puzzleGame == null) {

                } else if (currentQuestion.puzzleGame.equals("true") && hasPuzzled == false) {
                    PuzzleGame passport = new PuzzleGame();
                    passport.setVisible(true);
                    hasPuzzled = true;
                }
                if (currentQuestion.birdGame == null) {
                } else if (currentQuestion.birdGame.equals("true") && hasBirded == false) {
                    BirdMiniGame birdgame = new BirdMiniGame();
                    birdgame.setVisible(true);
                    hasBirded = true;
                }

                if (currentOption.pic == null) {
                    picplace.setVisible(false);
                    nameplace.setVisible(false);

                } else if (currentOption.pic.equals("true")) {

                    gameMethods.getVacationPicture(UserManager.getUserPicNumber(), nameplace, picplace);
                    picplace.setVisible(true);
                    nameplace.setVisible(true);
                }
            }

        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LandingScreen home = new LandingScreen();
        home.setVisible(true);
        dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JTextArea dialogue_area;
    private javax.swing.JLabel imagearea;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar loveBar;
    private javax.swing.JLabel nameplace;
    private javax.swing.JLabel picplace;
    // End of variables declaration//GEN-END:variables
}
